### ISSUE TITLE
plugin  does not work when i replace script file in body tag !!!

### ISSUE THREAD

**Issue by mhsohag11** [Tilotiti/jQuery-Google-Map#12]
When i call script file in body tag . Map not work. I found in your documantion site that you call all script file in head tag. How can work when i replace all script file in body tag.

Please , help !!!

**Comment by Tilotiti** [comment]
Then you must use the jquery function to load the function when everything is loaded : 

    <script>
        $(function() {
            $('#map') ....
        });
    <script>
