### ISSUE TITLE
Add Marker using coords

### ISSUE THREAD

**Issue by LenWright** [Tilotiti/jQuery-Google-Map#7]
hi,
when I use the AddMarker function with an address, the marker is draggable, and works fine. But if I supply coords [lat, long], then the marker is not draggable.

is it possible to fix this so that the marker is draggable with [lat,long]?

**Comment by Tilotiti** [comment]
Does it fix it ?

**Comment by LenWright** [comment]
hi,
looking at the code in your latest commit, it looks like this will fix it, since it looks about the same as what I did to try and resolve it on my own. I will download and test it tomorrow. thanks for taking care of this!
