### ISSUE TITLE
Multiple maps on page using address markers

### ISSUE THREAD

**Issue by joeomar** [Tilotiti/jQuery-Google-Map#8]
Hi. I have a page with four maps, similar to your sample page (map1, map2, map3, and map4). I'm adding markers using postal address ("address:") on all four maps, two markers per map. However, the first three maps don't display their markers, and the fourth map shows all the markers for all the maps; three maps with no markers and the fourth with all eight. If I change the addMarker to use "coords:" then the markers display correctly, two markers on each map. Any idea why this is happening?

**Comment by joeomar** [comment]
I've uploaded a very simplified page to demonstrate.  Again, if I convert all the addresses to coords, this displays correctly:
[http://www.joeomar.com/googleMapsSimple.html](http://www.joeomar.com/googleMapsSimple.html)

**Comment by Tilotiti** [comment]
Hi, sorry for the wait, I've updated the script with some bugfix, this one included.
Enjoy !
