### ISSUE TITLE
Get user's current location to draw route?

### ISSUE THREAD

**Issue by VeeK727** [Tilotiti/jQuery-Google-Map#9]
I hope this plugin is not inactive. I wanted to know how I could take the user's geolocation coordinates and use that to draw a route.

**Comment by Tilotiti** [comment]
Hi,

The easy way : 

    $(function() {
        $('#map').googleMap();
        navigator.geolocation.getCurrentPosition(function(position) {
            $('#map').addMarker({
                coords: [position.coords.latitude, position.coords.longitude]
            });
        });
    });
